version: 2
updates:
  - package-ecosystem: npm
    schedule:
      interval: weekly
      day: sunday
    groups:
      npm-dependencies:
        patterns:
          - "*"
    directories:
      - "/"
    commit-message:
      prefix: fix(dependabot)
    cooldown:
      default-days: 7
      exclude:
        - '@typeform/*'
    ignore:
      - dependency-name: semantic-release
        versions:
          - '>=25.0.0'
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: sunday
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    directories:
      - "/"
    commit-message:
      prefix: build(dependabot)
