name: 'CI Standard Checks'
description: 'Runs Standard Checks for Typeform'
author: 'Typeform'
inputs:
  skipChecks:
    required: true
    default: ''
    description: 'Checks to be skipped'
  enableChecks:
    required: true
    default: ''
    description: 'Optional checks to enable'
  githubToken:
    required: true
    description: 'Required for checks that need access to Github'
runs:
  using: 'node20'
  main: 'dist/index.js'
