name: 'CI Standard Checks'
description: 'Runs Standard Checks for Typeform'
author: 'Typeform'
inputs:
  skipChecks:
    required: true
    default: ''
    description: 'Checks to be skipped'
  enableChecks:
    required: true
    default: ''
    description: 'Optional checks to enable'
  githubToken:
    required: true
    description: 'The github token to get PR info when checking for Jira Issue key'
runs:
  using: 'node16'
  main: 'dist/index.js'
