name: 'CI Standard Checks'
description: 'Runs Standard Checks for Typeform'
author: 'Typeform'
inputs:
  docker-username:
    required: true
    description: 'The docker username'
  docker-password:
    required: true
    description: 'The docker password'
runs:
  using: 'node12'
  main: 'dist/index.js'
