name: 'release'
on:
  workflow_dispatch

jobs:
  release: # this releases in v1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update major version tag
        run: |
          git config --global user.email "seti@typeform.com"
          git config --global user.name "SETI Bot"
          git tag -fa v1 -m "Update ${TAG} tag"
          git push origin ${TAG} --force
        env:
          TAG: v1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
