name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Set GitHub packages registry
        run: |
          npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GH_TOKEN }}
          npm config set @typeform:registry https://npm.pkg.github.com/
      - uses: actions/checkout@v2
      - run: |
          yarn install
      - run: |
          yarn run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN  }}
          dockerUsername: ${{ secrets.GITLEAKS_DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.GITLEAKS_DOCKER_PASSWORD }}
